In [54]:
import pandas as pd
import numpy as np

def read_sheet(sheet, first):
    ''' Read a sheet from the JMP_2021_WLD.xlsx file and return a dataframe
    args.
        sheet: str, name of the sheet to read
        first: bool, whether this is the first sheet to be read
    returns.
        df: pd.DataFrame, the dataframe of the sheet
    '''
    # clean the dataframe of necessary columns
    df = pd.read_excel('initial/JMP_2021_WLD.xlsx', sheet_name=sheet)\
        .drop(columns=['sl','region_who','region_unicef_programme','region_unicef_reporting'], axis=1)\
        .rename({'name': 'country', 'pop_n': 'pop', 'prop_u': 'pop_urban'}, axis=1)\
        .dropna(subset=['country'])\
        .set_index(['country', 'iso3', 'region_sdg', 'year'])
    if not first:
        df = df.drop(columns=['pop', 'pop_urban'], axis=1)
    return df

wat = read_sheet('wat', first=True)
hyg = read_sheet('hyg', first=False)
san = read_sheet('san', first=False)

comb_df = pd.concat([wat, hyg, san], axis=1, join='inner')

cols = [col for col in comb_df.columns if 'arc' not in col]
pop_df = comb_df.copy()
pop_df[cols] = pop_df.loc[:,cols].multiply(comb_df['pop'], axis=0) * 10
pop_df['pop'] = comb_df['pop'] * 1000
pop_df

                                                          pop     pop_urban  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  2.077996e+07  4.587799e+06
                                           2001  2.160699e+07  4.790054e+06
                                           2002  2.260077e+07  5.031158e+06
                                           2003  2.368087e+07  5.293385e+06
                                           2004  2.472669e+07  5.563505e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  1.403034e+07  4.531238e+06
                                           2017  1.423660e+07  4.589452e+06
                                           2018  1.443881e+07  4.650597e+06
                                           2019  1.464547e+07  4.717307e+06
                                           2020  1.486293e+07  4.792105e+06

                                                    wat_bas_n     wat_lim_n  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  5.854008e+06  7.606791e+05
                                           2001  6.093035e+06  7.911491e+05
                                           2002  6.833657e+06  8.926112e+05
                                           2003  7.642699e+06  1.003395e+06
                                           2004  8.488316e+06  1.118861e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  9.045214e+06  1.797998e+06
                                           2017  9.110943e+06  1.874760e+06
                                           2018  9.174244e+06  1.951685e+06
                                           2019  9.240555e+06  2.029876e+06
                                           2020  9.314070e+06  2.110170e+06

                                                  wat_unimp_n     wat_sur_n  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  8.972433e+06  5.192837e+06
                                           2001  9.327207e+06  5.395601e+06
                                           2002  9.422176e+06  5.452329e+06
                                           2003  9.522299e+06  5.512479e+06
                                           2004  9.575232e+06  5.544279e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  2.243020e+06  9.441063e+05
                                           2017  2.287680e+06  9.632162e+05
                                           2018  2.331113e+06  9.817697e+05
                                           2019  2.374697e+06  1.000344e+06
                                           2020  2.419366e+06  1.019321e+06

                                                 arc_wat_bas_n     wat_bas_r  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000       2.346000  4.444832e+06
                                           2001       2.346000  4.621735e+06
                                           2002       2.346000  5.279554e+06
                                           2003       2.346000  5.998394e+06
                                           2004       2.346000  6.750433e+06
...                                                        ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016      -0.460146  7.106665e+06
                                           2017      -0.460146  7.126328e+06
                                           2018      -0.460146  7.141851e+06
                                           2019      -0.460146  7.157469e+06
                                           2020      -0.460146  7.176182e+06

                                                    wat_lim_r   wat_unimp_r  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  7.151127e+05  9.515176e+06
                                           2001  7.435739e+05  9.893876e+06
                                           2002  8.494081e+05  1.003838e+07
                                           2003  9.650596e+05  1.019273e+07
                                           2004  1.086052e+06  1.030311e+07
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  2.362707e+06  3.172863e+06
                                           2017  2.460232e+06  3.233721e+06
                                           2018  2.558542e+06  3.294067e+06
                                           2019  2.659111e+06  3.355836e+06
                                           2020  2.763164e+06  3.420501e+06

                                                 ...      san_sep_r  \
country     iso3 region_sdg                year  ...
Afghanistan AFG  Central and Southern Asia 2000  ...  233549.210377
                                           2001  ...  242844.388775
                                           2002  ...  254013.652786
                                           2003  ...  266153.040484
                                           2004  ...  277907.157764
...                                              ...            ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  ...  328417.900425
                                           2017  ...  356592.573657
                                           2018  ...  385335.713450
                                           2019  ...  414868.077798
                                           2020  ...  445401.684987

                                                     san_sew_r      san_sm_u  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  120302.524162           NaN
                                           2001  125090.523325           NaN
                                           2002  137258.669536           NaN
                                           2003  150539.661864           NaN
                                           2004  164206.140552           NaN
...                                                        ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  236578.372683  2.576948e+06
                                           2017  217830.025992  2.530379e+06
                                           2018  198382.031829  2.480907e+06
                                           2019  178356.816708  2.430022e+06
                                           2020  157800.909211  2.378672e+06

                                                  san_sdo_sm_u  san_fst_sm_u  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000            NaN           NaN
                                           2001            NaN           NaN
                                           2002            NaN           NaN
                                           2003            NaN           NaN
                                           2004            NaN           NaN
...                                                        ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  816842.446637  17183.331329
                                           2017  800785.692554  17753.692507
                                           2018  783855.400042  18272.768752
                                           2019  766526.746248  18748.886482
                                           2020  749100.340664  19188.055447

                                                 san_sew_sm_u  arc_san_sm_u  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000           NaN           NaN
                                           2001           NaN           NaN
                                           2002           NaN           NaN
                                           2003           NaN           NaN
                                           2004           NaN           NaN
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  1.742922e+06     -0.486016
                                           2017  1.711840e+06     -0.486016
                                           2018  1.678779e+06     -0.486016
                                           2019  1.644746e+06     -0.486016
                                           2020  1.610383e+06     -0.486016

                                                    san_lat_u     san_sep_u  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  2.625991e+06  5.251586e+06
                                           2001  2.730504e+06  5.460597e+06
                                           2002  3.347724e+06  5.711749e+06
                                           2003  4.022842e+06  5.984716e+06
                                           2004  4.738383e+06  6.249019e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  1.090968e+06  1.402996e+06
                                           2017  1.068780e+06  1.500917e+06
                                           2018  1.045191e+06  1.600629e+06
                                           2019  1.020826e+06  1.703053e+06
                                           2020  9.960753e+05  1.809036e+06

                                                    san_sew_u
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  1.552249e+06
                                           2001  1.614028e+06
                                           2002  1.705632e+06
                                           2003  1.805344e+06
                                           2004  1.904076e+06
...                                                       ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  1.105729e+07
                                           2017  1.120621e+07
                                           2018  1.135156e+07
                                           2019  1.150001e+07
                                           2020  1.165653e+07

[4914 rows x 92 columns]

In [60]:
gdp = pd.read_csv('initial data/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_5358352.csv', header=2)\
    .rename({'Country Code': 'iso3'}, axis=1)\
    .drop(columns=['Country Name', 'Indicator Name', 'Indicator Code', 'Unnamed: 66'], axis=1)
gdp = pd.melt(gdp, id_vars=['iso3'], var_name='year', value_name='gdp')
gdp.year = gdp.year.astype('float64')
all = pop_df.join(gdp.set_index(['iso3', 'year']), on=['iso3', 'year'], how='left')

                                                          pop     pop_urban  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  2.077996e+07  4.587799e+06
                                           2001  2.160699e+07  4.790054e+06
                                           2002  2.260077e+07  5.031158e+06
                                           2003  2.368087e+07  5.293385e+06
                                           2004  2.472669e+07  5.563505e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  1.403034e+07  4.531238e+06
                                           2017  1.423660e+07  4.589452e+06
                                           2018  1.443881e+07  4.650597e+06
                                           2019  1.464547e+07  4.717307e+06
                                           2020  1.486293e+07  4.792105e+06

                                                    wat_bas_n     wat_lim_n  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  5.854008e+06  7.606791e+05
                                           2001  6.093035e+06  7.911491e+05
                                           2002  6.833657e+06  8.926112e+05
                                           2003  7.642699e+06  1.003395e+06
                                           2004  8.488316e+06  1.118861e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  9.045214e+06  1.797998e+06
                                           2017  9.110943e+06  1.874760e+06
                                           2018  9.174244e+06  1.951685e+06
                                           2019  9.240555e+06  2.029876e+06
                                           2020  9.314070e+06  2.110170e+06

                                                  wat_unimp_n     wat_sur_n  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  8.972433e+06  5.192837e+06
                                           2001  9.327207e+06  5.395601e+06
                                           2002  9.422176e+06  5.452329e+06
                                           2003  9.522299e+06  5.512479e+06
                                           2004  9.575232e+06  5.544279e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  2.243020e+06  9.441063e+05
                                           2017  2.287680e+06  9.632162e+05
                                           2018  2.331113e+06  9.817697e+05
                                           2019  2.374697e+06  1.000344e+06
                                           2020  2.419366e+06  1.019321e+06

                                                 arc_wat_bas_n     wat_bas_r  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000       2.346000  4.444832e+06
                                           2001       2.346000  4.621735e+06
                                           2002       2.346000  5.279554e+06
                                           2003       2.346000  5.998394e+06
                                           2004       2.346000  6.750433e+06
...                                                        ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016      -0.460146  7.106665e+06
                                           2017      -0.460146  7.126328e+06
                                           2018      -0.460146  7.141851e+06
                                           2019      -0.460146  7.157469e+06
                                           2020      -0.460146  7.176182e+06

                                                    wat_lim_r   wat_unimp_r  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  7.151127e+05  9.515176e+06
                                           2001  7.435739e+05  9.893876e+06
                                           2002  8.494081e+05  1.003838e+07
                                           2003  9.650596e+05  1.019273e+07
                                           2004  1.086052e+06  1.030311e+07
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  2.362707e+06  3.172863e+06
                                           2017  2.460232e+06  3.233721e+06
                                           2018  2.558542e+06  3.294067e+06
                                           2019  2.659111e+06  3.355836e+06
                                           2020  2.763164e+06  3.420501e+06

                                                 ...      san_sew_r  \
country     iso3 region_sdg                year  ...
Afghanistan AFG  Central and Southern Asia 2000  ...  120302.524162
                                           2001  ...  125090.523325
                                           2002  ...  137258.669536
                                           2003  ...  150539.661864
                                           2004  ...  164206.140552
...                                              ...            ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  ...  236578.372683
                                           2017  ...  217830.025992
                                           2018  ...  198382.031829
                                           2019  ...  178356.816708
                                           2020  ...  157800.909211

                                                     san_sm_u   san_sdo_sm_u  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000           NaN            NaN
                                           2001           NaN            NaN
                                           2002           NaN            NaN
                                           2003           NaN            NaN
                                           2004           NaN            NaN
...                                                       ...            ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  2.576948e+06  816842.446637
                                           2017  2.530379e+06  800785.692554
                                           2018  2.480907e+06  783855.400042
                                           2019  2.430022e+06  766526.746248
                                           2020  2.378672e+06  749100.340664

                                                 san_fst_sm_u  san_sew_sm_u  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000           NaN           NaN
                                           2001           NaN           NaN
                                           2002           NaN           NaN
                                           2003           NaN           NaN
                                           2004           NaN           NaN
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  17183.331329  1.742922e+06
                                           2017  17753.692507  1.711840e+06
                                           2018  18272.768752  1.678779e+06
                                           2019  18748.886482  1.644746e+06
                                           2020  19188.055447  1.610383e+06

                                                 arc_san_sm_u     san_lat_u  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000           NaN  2.625991e+06
                                           2001           NaN  2.730504e+06
                                           2002           NaN  3.347724e+06
                                           2003           NaN  4.022842e+06
                                           2004           NaN  4.738383e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016     -0.486016  1.090968e+06
                                           2017     -0.486016  1.068780e+06
                                           2018     -0.486016  1.045191e+06
                                           2019     -0.486016  1.020826e+06
                                           2020     -0.486016  9.960753e+05

                                                    san_sep_u     san_sew_u  \
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000  5.251586e+06  1.552249e+06
                                           2001  5.460597e+06  1.614028e+06
                                           2002  5.711749e+06  1.705632e+06
                                           2003  5.984716e+06  1.805344e+06
                                           2004  6.249019e+06  1.904076e+06
...                                                       ...           ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  1.402996e+06  1.105729e+07
                                           2017  1.500917e+06  1.120621e+07
                                           2018  1.600629e+06  1.135156e+07
                                           2019  1.703053e+06  1.150001e+07
                                           2020  1.809036e+06  1.165653e+07

                                                          gdp
country     iso3 region_sdg                year
Afghanistan AFG  Central and Southern Asia 2000           NaN
                                           2001           NaN
                                           2002  3.854235e+09
                                           2003  4.539501e+09
                                           2004  5.220824e+09
...                                                       ...
Zimbabwe    ZWE  Sub-Saharan Africa        2016  2.054868e+10
                                           2017  1.758489e+10
                                           2018  3.415607e+10
                                           2019  2.183223e+10
                                           2020  2.150970e+10

[4914 rows x 93 columns]

In [56]:
pop_df.index.dtypes

country       object
iso3          object
region_sdg    object
year           int64
dtype: object

In [57]:
gdp.dtypes

iso3     object
year     object
gdp     float64
dtype: object